### ISSUE TITLE
API Response 페이지네이션 totalElements 반환 방식 논의

### ISSUE THREAD

**Issue by ParkJeongseop** [f-lab-clone/ticketing-backend#113]
# Description
페이지네이션 구현과 관련하여 현재 전체 데이터 건수를 totalElements ResponseDto에 별도로 추가하여 구현되어있습니다.
이부분을 아래 두 방식중에 어떤 방식을 사용하는 것이 일관적이고 좋을지 논의 필요.

Best Practice나 참고 링크가 첨부되면 더 좋습니다.

```json
{
     "totalElements": 10,
     "data": []
}
```

```json
{
    "data": {
        "list": [],
        "totalElements": 10
    } 
}
```
# To do

# Test Checklist

**Comment by junha-ahn** [comment]
kakao api docs 등의 레퍼런스를 참고하면 좋을것 같습니다.

> 해당 이슈는 #99 에도 의존성이 좀 있죠 (totalCount 자체를 없앨 수도…)

**Comment by junha-ahn** [comment]
Data와 별도로 키를 구성하네요.

<img width="806" alt="image" src="https://github.com/f-lab-clone/ticketing-backend/assets/41976906/02230e45-6357-406c-9bfe-7f20a7206a9b">
> [카카오](https://developers.kakao.com/docs/latest/ko/daum-search/dev-guide)


<img width="458" alt="image" src="https://github.com/f-lab-clone/ticketing-backend/assets/41976906/f0ab9d94-252a-454d-973d-71de428bb597">
> [쿠팡](https://developers.coupangcorp.com/hc/ko/articles/360033644754-%EC%B6%9C%EA%B3%A0%EC%A7%80-%EC%A1%B0%ED%9A%8C)

**Comment by junha-ahn** [comment]
<img width="856" alt="image" src="https://github.com/f-lab-clone/ticketing-backend/assets/41976906/25f0efc0-09e8-47e5-95d1-3bc3fa6c7bf4">

#99  의 [댓글](https://github.com/f-lab-clone/ticketing-backend/issues/99#issuecomment-1756778034)에 따라 totalCount를 `/events` endpoint에서는 노출하지 않겠습니다.

제거해주세요.
