### ISSUE TITLE
API Docs 자동화

### ISSUE THREAD

**Issue by junha-ahn** [f-lab-clone/ticketing-backend#37]
# Description

reference
- [참고](https://velog.io/@city7310/%EB%B0%B1%EC%97%94%EB%93%9C%EA%B0%80-%EC%9D%B4%EC%A0%95%EB%8F%84%EB%8A%94-%ED%95%B4%EC%A4%98%EC%95%BC-%ED%95%A8-6.-API-%EC%8A%A4%ED%8E%99-%EC%84%A4%EA%B3%84%EC%99%80-%EB%AC%B8%EC%84%9C%ED%99%94-%EB%B0%A9%EC%8B%9D-%EA%B2%B0%EC%A0%95-2)
- [swagger](https://tecoble.techcourse.co.kr/post/2020-08-18-spring-rest-docs/)
- [git book](https://app.gitbook.com/@junha-ahn-dev/s/memo-back/)
- etc...

개인적으로는 Git book과 같은 별도 호스팅 방식을 선호합니다.

앞으로 지속적으로 서버를 띄울 수는 없는 입장에서 Swagger는 항시 유지가 불가능하기 때문입니다. 

물런 자동화가 더 중요하다고 생각하기 때문에 우선순위는 다음과 같습니다.

1. 자동 생성 + 무료 호스팅
2. 자동 생성 + 자체 호스팅 (Swagger)
3. 수동 생성 + 무료 호스팅

> Git actions로 swagger output html을 생성한 후 git html 무료 호스팅등을 이용하는 방법도 생각나네요 (가능하다면)
아니면 Git Book 이 자동으로 생성된다면?...

# To do
- 자동 API Docs 생성
- 무료 호스팅

# Test Checklist

**Comment by ParkJeongseop** [comment]
1번의 자동 생성 + 무료 호스팅을 Swagger와 GitPages로 테스트해보았습니다. 
API문서 배포용 레포지토리 생성하여 깃페이지로 웹호스팅을 하고, 개발레포지토리에서 생성되는 swagger yaml파일을 참조하는 방식입니다.

[Swagger API문서](https://www.parkjeongseop.com/swagger-test/)
[Swagger 호스팅용 레포지토리](https://github.com/ParkJeongseop/swagger-test)
[별도 yaml파일 소유 레포지토리](https://github.com/ParkJeongseop/swagger-test-1)
https://github.com/ParkJeongseop/swagger-test/blob/master/dist/swagger-initializer.js

**Comment by junha-ahn** [comment]
@ParkJeongseop API docs Json beautifier (linux) 부탁드립니다.
