### ISSUE TITLE
컨벤션 정의: Time 

### ISSUE THREAD

**Issue by junha-ahn** [f-lab-clone/ticketing-backend#39]
# Description

[참고](https://velog.io/@city7310/%EB%B0%B1%EC%97%94%EB%93%9C%EA%B0%80-%EC%9D%B4%EC%A0%95%EB%8F%84%EB%8A%94-%ED%95%B4%EC%A4%98%EC%95%BC-%ED%95%A8-12.-%EC%96%B4%ED%94%8C%EB%A6%AC%EC%BC%80%EC%9D%B4%EC%85%98-%EB%A0%88%EB%B2%A8-%EC%9D%98%EC%82%AC%EA%B2%B0%EC%A0%95-2#%EC%8B%9C%EA%B0%81-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%A0%80%EC%9E%A5-%EB%B0%A9%EC%8B%9D) 하여 애플리케이션에서 Time 데이터를 다루는 방법을 정의해주세요

# To do
- 모든 Time Data에 대한 방식 정의 (선언, 자료형, 규칙 등)
- DB, 내부 애플리케이션 자료형, HTTP requeset/response 포함
- 패키지 정리

# Test Checklist

**Comment by bohblue2** [comment]
(Wiki datetime format rule)[https://github.com/f-lab-clone/ticketing-service/wiki/Convention#datetime-format-rule] 문서 작성했습니다.

**Comment by junha-ahn** [comment]
@bohblue2 

## 타임존 설정

>  UTC 등 타임존 설정은 하지 않고 모든 시간은 KST 타임존으로 간주 한다.

동의하기 어렵습니다. 일단 한국에서 실제 서비스를 운영한다고 생각해도, 엄청난 혼란이 생길겁니다.  

특히 간주한다 부분이 정말 큰 문제를 발생시킵니다
- 예를들어 App local 환경에서는 1일 13시지만, Prod 환경에서는 1일 4시이거나, App 에서는 x시로 출력... DB에서는 x시로 출력...  

Time 정보라는건, 해당 서버에서만, 개발할때만 문제가 없으면 되는게 아니라 모든 서버(App, Database, Redis, LB 등)와 모든 환경(local, Prod)에서도 문제가 없어야 합니다.

**모든 환경에서 명시적**으로 Timezone을 설정해야 하는데, 그렇기 때문에 UTC를 사용해야 합니다. 

사진 첨부합니다.

![image](https://github.com/f-lab-clone/ticketing-service/assets/41976906/78731eae-de20-41df-b579-99fff2ec806e)
> [출처](https://velog.io/@city7310/%EB%B0%B1%EC%97%94%EB%93%9C%EA%B0%80-%EC%9D%B4%EC%A0%95%EB%8F%84%EB%8A%94-%ED%95%B4%EC%A4%98%EC%95%BC-%ED%95%A8-12.-%EC%96%B4%ED%94%8C%EB%A6%AC%EC%BC%80%EC%9D%B4%EC%85%98-%EB%A0%88%EB%B2%A8-%EC%9D%98%EC%82%AC%EA%B2%B0%EC%A0%95-2#%EC%8B%9C%EA%B0%81-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%A0%80%EC%9E%A5-%EB%B0%A9%EC%8B%9D) 


## ISO string parsing

```kotlin
val FORMATTER = "yyyy-MM-dd'T'HH:mm:ss.SSSSSS".let { DateTimeFormatter.ofPattern(it) }

// LocalDatetime to String
localDateTimeString = FORMATTER.format(localDateTimeObj) 
// String to LocalDatetime
localDateTimeObj = FORMATTER.parse(localDateTimeString)
```

더 깔끔한 방법 없습니까?

모든 코드에서 시간이 나올때마다 해당 코드를 복붙해야하는건 아닐탠데 더 정리되었으면 좋겠습니다.

**Comment by bohblue2** [comment]
## Iso8601 String Parsing/Converting
Iso8601 포맷을 파싱 및 컨버팅 하는 로직은 주로 (De)Serializer 에서 이루어집니다. 

DatetimeConverter 안에 Parsing/Converting 하는 로직을 미리 만들어두고 `GsonBuilder`에 `registerTypeAdapter` 를 지정해 두면 짧은 코드를 만들 수 있습니다.

```kotlin

class DateTimeConverter : JsonSerializer<LocalDateTime>, JsonDeserializer<LocalDateTime> {
    private val FORMATTER = "yyyy-MM-dd'T'HH:mm:ss.SSSSSSS"
        .let { DateTimeFormatter.ofPattern(it) }

    override fun serialize(src: LocalDateTime?, typeOfSrc: Type?, context: JsonSerializationContext?): JsonElement {
        return JsonPrimitive(FORMATTER.format(src))
    }

    override fun deserialize(json: JsonElement?, typeOfT: Type?, context: JsonDeserializationContext?): LocalDateTime? {
        return FORMATTER.parse(json!!.asJsonPrimitive.asString) as LocalDateTime?
    }
}

private val samplePerformanceCreateRequest: PerformanceCreateRequest = PerformanceCreateRequest(
    title = "test title",
    date = LocalDateTime.now(),
    bookingEndTime = LocalDateTime.now() + Duration.ofHours(2),
    bookingStartTime = LocalDateTime.now() + Duration.ofHours(1),
    maxAttendees = 10
)

private val gson: Gson = GsonBuilder().registerTypeAdapter(LocalDateTime::class.java, DateTimeConverter()).create()

// Serialize
jsonObj = gson.toJson(samplePerformanceCreateRequest)

// Deserialize
Obj = gson.fromJson(jsonObj)
```

# (De)Serializer
추가 코드 작성해두었습니다.

**Comment by junha-ahn** [comment]
좋습니다! Timezone 이슈도 정리 후 Wiki에 옮겨주세요!

**Comment by junha-ahn** [comment]
@bohblue2 

> java.time.LocalDatetime.utcnow() 메서드를 통해 UTC 표준시를 사용한다.

개발자가 모든 개발 과정 (몇개월)동안 기억하기 힘듭니다. 

그것보다 java env 주입등을 통해 timezone 설정을 다룰 수 있는 방법 없을까요?

**Comment by junha-ahn** [comment]
개인적으로는 해당 이슈에 대해서 feat 브랜치 생성 후 

UTC Time에 관련된 유닛 테스트 [사례](https://velog.io/@jehjong/JavaScript-%EC%84%9C%EB%B2%84%EC%99%80-%EB%A1%9C%EC%BB%AC%EC%9D%98-%EC%8B%9C%EA%B0%84%EC%B0%A8-timezone-%EB%AC%B8%EC%A0%9C)를 작성해주셨으면 좋겠습니다.

**Comment by junha-ahn** [comment]
# 테스트 작성

해당 이슈에 대해서 feat 브랜치 생성 후 UTC Time에 관련된 유닛 테스트 [사례](https://velog.io/@jehjong/JavaScript-%EC%84%9C%EB%B2%84%EC%99%80-%EB%A1%9C%EC%BB%AC%EC%9D%98-%EC%8B%9C%EA%B0%84%EC%B0%A8-timezone-%EB%AC%B8%EC%A0%9C)를 작성부탁드립니다.
- 해당 이슈에 [enhancement](https://github.com/f-lab-clone/ticketing-service/labels/enhancement) 라벨 추가

그리고 위키에서 해당 테스트 파일(`src/test/.../TimeTest.kt`) 링크를 첨부해서 쉽게 확인할 수 있을것이라고 생각합니다.
- timezone 관련 테스트
- serialize/deserialize 관련 테스트

> 다만 먼저 event 통합 테스트 작성부터 부탁드립니다.

**Comment by bohblue2** [comment]
> ```kotlin
> ```kotlin
> override fun serialize(src: LocalDateTime?, typeOfSrc: Type?, context: JsonSerializationContext?): JsonElement {
>       return JsonPrimitive(FORMATTER.format(src))
>   }
> 
>   override fun deserialize(json: JsonElement?, typeOfT: Type?, context: JsonDeserializationContext?): LocalDateTime? {
>       return FORMATTER.parse(json!!.asJsonPrimitive.asString) as LocalDateTime?
>   }
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> (typeOfSrc: Type?, context: JsonSerializationContext?)는 왜 받는건가요? 목적이 궁금합니다
> ```

이러한 매개변수들은 Gson 라이브러리의 `JsonSerializer`와 `JsonDeserializer` 인터페이스에 정의된 함수들에 필요한 매개변수입니다. 이 인터페이스들을 구현할 때 이러한 매개변수들이 필요합니다. 이 매개변수들의 용도는 다음과 같습니다.

1. `typeOfSrc` (Type): 이 매개변수는 객체가 가진 실제 타입을 나타냅니다. Gson은 이 정보를 사용하여 제네릭 타입을 올바르게 처리합니다. 이 정보가 없다면, 제네릭 타입이 erase되어 버려서 특정 상황에서는 잘못된 타입으로 데이터를 처리할 수 있습니다.

2. `context` (JsonSerializationContext or JsonDeserializationContext): 이 매개변수는 객체 내부의 다른 객체를 직렬화 또는 역직렬화하는 데 사용됩니다. 예를 들어, 여러분이 직렬화하려는 객체가 다른 복잡한 객체를 필드로 가지고 있는 경우, 이 `context`를 사용하여 내부 객체를 쉽게 직렬화하거나 역직렬화할 수 있습니다.

하지만, 여러분이 제공한 코드에서는 `typeOfSrc`와 `context`가 실제로 사용되지 않고 있습니다. 이는 LocalDateTime을 직렬화하고 역직렬화하는 데에 이런 추가적인 정보가 필요하지 않기 때문입니다. 이런 경우에는, 매개변수들이 사용되지 않아도 무방합니다. 그러나 인터페이스를 구현할 때는 이러한 매개변수들을 포함시키는 것이 필요합니다.

**Comment by junha-ahn** [comment]
연관 PR #55 을 더 참고해주세요. 
- `OffsetDateTime`을 사용합니다.
