### ISSUE TITLE
회원 기능 구현

### ISSUE THREAD

**Issue by junha-ahn** [f-lab-clone/ticketing-backend#4]
# Description

회원에 관련된 기능을 구현해주세요

# To do
- 회원은 username, password, name 정보를 가집니다.
- 회원가입 
- 로그인 (JWT, Local-Session 중 하나 선택)
    - 향후: JWT, Session등 다양한 로그인을 고려한 인터페이스/클래스 설계
- 비밀번호 Hasing 후 Insert
- 실제 DB를 사용하지 않아도 됩니다. (Mockup test only)

# Test Checklist

**Comment by minjun3021** [comment]
# Test Checklist

controller
- contoller.register(...)는 userService.create()를 호출해야 한다.
- controller.register(...)가 정상적으로 호출되면 200 success를 반환한다.
- controller.register(...)에 빈값을 넣으면 401 error를 반환한다.

service
- service.create()는 repository.create()를 호출한다

repository
- ...
