### ISSUE TITLE
PK Int vs Long

### ISSUE THREAD

**Issue by junha-ahn** [f-lab-clone/ticketing-backend#50]
# Description

https://github.com/f-lab-clone/ticketing-service/pull/28#discussion_r1268185244 에 대해 해당 이슈에 코멘트로 정리 부탁드립니다.

# To do
- 각각의 장단점
- 우리 프로젝트가 어떤걸 선택할지
- 해당 이슈를 통해 다른 모든 PK type 통일화 (`feat/50-event-pk-type-integration`)

**Comment by ParkJeongseop** [comment]
Kotlin에서 int와 long은 MySQL에서 int, bigint로 대응됩니다.
int: 32 bits -2147483648 ~ 2147483647
long: 64 bits -9223372036854775808 ~ 9223372036854775807

int의 장점
 - 빠른 성능
long의 장점
 - 대규모 사용자 서비스가 되었을때 따로 대응 불필요

조사해본결과 위와같이 정리해볼 수 있었는데, 대규모 서비스를 목표로 하기때문에 long을 사용하는 것이 좋을것같습니다.

**Comment by junha-ahn** [comment]
1. 저희는 대규모 트래픽을 목표로 하고 있고, 대규모 사용자는 다른 영역 같습니다.
2. INT, Long을 사용하고 x건의 데이터를 저장했을때 **데이터 크기의 차이**를 비교해주시면 좋을것 같습니다.

관련 자료
- https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=rosa0189&logNo=60159593857
- https://leo-bb.tistory.com/83

**Comment by junha-ahn** [comment]
속도 관련 자료는 `tinyint` vs `int`에서 더 많이 찾을 수 있네요.

여러 비교를 Int vs Bigint로도 부탁드립니다.

- https://dba.stackexchange.com/questions/212488/is-there-a-performance-benefit-to-use-tinyint-instead-of-int-for-primary-key
- https://shanewelgama.wordpress.com/2020/08/16/tinyint-vs-smallint-vs-int-vs-bigint-does-size-matter/
- 그 외 검색

**Comment by ParkJeongseop** [comment]
[SQL Server Int or BigInt database table Ids](https://stackoverflow.com/questions/2124631/sql-server-int-or-bigint-database-table-ids)

> Even if the machine's native word size is 64 bits, that only means that 64-bit CPU operations won't be any slower than 32-bit operations. Most of the time, they also won't be faster, they'll be the same. But most databases are not going to be CPU bound anyway, they'll be I/O bound and to a lesser extent memory-bound, so a 50%-90% smaller data size is a Very Good Thing when you need to perform an index scan over 200 million rows.

[IMPACT OF COLUMN TYPES ON MYSQL JOIN PERFORMANCE](https://fromdual.com/impact-of-column-types-on-mysql-join-performance)
위 퍼포먼스 테스트 결과를 보면 조인할때 BigInt는 Int에 비해 7%느렸습니다. 해당 테스트는 메모리상에서 이루어졌고, 실제 환경에서 디스크 I/O가 일어나면 BigInt는 Int의 2배의 저장공간을 사용하기에 그만큼 더 느려질 것 입니다.

64비트 컴퓨팅 환경에서 CPU와 메모리상에서 BigInt와 Int의 퍼포먼스 차이는크지않더라도 I/O가 저장공간 만큼 더일어날것이므로 저희 서비스에 환경에 맞게 Fit한 타입으로 지정하는것이 좋겠습니다.

**Comment by junha-ahn** [comment]
조사 감사합니다.

해당 이슈는 PK INT를 사용한다고 결론 내리고 CLOSE하겠습니다!
