### ISSUE TITLE
예약 동시성 이슈 관련 구현

### ISSUE THREAD

**Issue by junha-ahn** [f-lab-clone/ticketing-backend#54]
# Description

Event 정보에는 최대 몇명의 사람이 예매 가능한지 정보가 있습니다.

간단한 로직
```kotlin
val event = getEvent(eventID)
if event.limit < event.reserved + 1 {
  throw Exception
}
return insertReservation(...)
```

만약 최대 10명의 사람이 예약 가능하다고 했을때, 100개의 Multi-Thread를 사용해 동시 Reservation 요청을 보낸다면 분명 동시성 이슈가 발생할 것으로 생각합니다.

먼저 해당 동시성 이슈가 실제로 존재하는지 확인하는 테스트 코드를 작성해주세요

그리고 해결 하기 위한 방법을 고려해주세요 (키워드 Lock)

# To do
- [ ] 동시성 이벤트 테스트 코드 작성
- [ ] 해결 하기 위한 방법 조사 후 댓글 작성
- [ ] 선택된 방법을 예약 로직에 구현

# Test Checklist

**Comment by junha-ahn** [comment]
### 참고 레퍼런스

`쿠폰/선착순 동시성 문제` 키워드로 검색했습니다

- [선착순 쿠폰 발급을 만들어보며 배우는 동시성 제어 (Select For Update)](https://blog.huni.kr/posts/%EC%84%A0%EC%B0%A9%EC%88%9C-%EC%BF%A0%ED%8F%B0-%EB%B0%9C%EA%B8%89%EC%9D%84-%EA%B5%AC%ED%98%84%ED%95%B4%EB%B3%B4%EB%A9%B0-%EB%B0%B0%EC%9A%B0%EB%8A%94-%EB%8F%99%EC%8B%9C%EC%84%B1-%EC%A0%9C%EC%96%B4-(%EB%B9%84%EA%B4%80%EC%A0%81-%EB%9D%BD)/)
    - Redis를 통해 학습하지만 Database에도 동일한 접근 방식을 사용
- [동시성 문제 해결하기 V1 - 낙관적 락(Optimistic Lock) feat.데드락 첫 만남](https://velog.io/@znftm97/%EB%8F%99%EC%8B%9C%EC%84%B1-%EB%AC%B8%EC%A0%9C-%ED%95%B4%EA%B2%B0%ED%95%98%EA%B8%B0-V1-%EB%82%99%EA%B4%80%EC%A0%81-%EB%9D%BDOptimisitc-Lock-feat.%EB%8D%B0%EB%93%9C%EB%9D%BD-%EC%B2%AB-%EB%A7%8C%EB%82%A8)
    - 멀티 쓰레드, JPA, Lock 등 기술 사용  
- [선착순 이벤트 시스템에서 발생가능한 동시성 문제와 해결 방안 탐구(redis, kafka)](https://upcurvewave.tistory.com/482)
    - 물런 redis/kafka를 이용한 해결 방법은 다음 스텝에서 사용한다 (현재는 Lock만 사용)
- [Spring& Java 재고시스템으로 알아보는 동시성이슈 해결방법](https://thalals.tistory.com/370)

**Comment by junha-ahn** [comment]
# 동시성 테스트

![image](https://github.com/f-lab-clone/ticketing-backend/assets/41976906/b263a858-79f6-4041-a907-5e8e48b865fa)
> https://github.com/f-lab-clone/ticketing-backend/blob/61c3f007f657da301b442d349528203ee44b52af/src/main/kotlin/com/group4/ticketingservice/service/ReservationService.kt#L22

![image](https://github.com/f-lab-clone/ticketing-backend/assets/41976906/3afc8f6a-3d46-4826-a03a-2086a4176a86)
> https://github.com/f-lab-clone/ticketing-backend/blob/61c3f007f657da301b442d349528203ee44b52af/src/integrationTest/kotlin/com/group4/ticketingservice/Reservation/ReservationTest.kt#L67

![image](https://github.com/f-lab-clone/ticketing-backend/assets/41976906/8a0226ed-3d2e-422d-92d3-b76d4888962f)
> https://github.com/f-lab-clone/ticketing-backend/actions/runs/5848327610/job/15855512710

**Comment by minjun3021** [comment]
### DB LOCK with JPA 
MYSQL의 스토리지 엔진인 innodb는 
동시성 문제와 데이터 일관성 유지에 중요한 역할을 하는 다양한 종류의 락을 지원한다.

하지만 JPA에서는 모든 종류의 락을  지원하지는 않는다.
만약 지원하게 된다면 
어떤 DBMS에서도 애플리케이션 코드를 돌아갈 수 있게 하는 이식성이 낮아지기 때문이다.

그래서 JPA는 RDBMS가 공통적으로 지원하는 락을 지원한다.

JPA는 동시성 제어를 위하여 두가지의 락 메커니즘을 사용

**낙관적 락**
> 데이터 충돌이 드물게 일어난다고 생각 하고 
어플리케이션 단에서 JPA가 버전관리를 통하여 동시성 제어를 하는 방법.
실제로 DB레벨 에서 LOCK이 일어나진 않는다.

**비관적 락**
> 무조건 db를 접근할때 동시성 관련 이슈가 생긴다고 가정하고 락을 진행시키는 방법.

` @Lock(value = LockModeType.PESSIMISTIC_WRITE)
    @Query("select e from Event e where e.id = :id")
    fun findByIdWithPesimisticLock(id: Long): Event?`

@Lock(value = LockModeType.PESSIMISTIC_WRITE) 어노테이션을 이용하여 락을 건다 .
LockModeType을 통하여 어떤 락을 사용할것인지 설정 가능하다.
SQL쿼리로 변환 될때 끝에 FOR UPDATE 절이 붙게 되는데
이 절이 붙은 쿼리가 반환하는 행들에 대하여 베타적 락이 일어나게 된다.
베타적 락은 Transaction이 시작 될때 획득하고 끝날때 반환한다. 


티켓팅 서비스를 구현하는 우리 프로젝트를 봤을때
무조건 어플리케이션 로직에서 동시성 관련 이슈가 생길수 밖에 없는 구조이므로
비관적락을 선택하였다.


자세한 설명 
[DB LOCK with JPA](https://minjun3021.notion.site/DB-LOCK-with-JPA-34318e92f21b41dc9caf11f0e4d2d023)
