### ISSUE TITLE
대기열 시스템 설계

### ISSUE THREAD

**Issue by junha-ahn** [f-lab-clone/ticketing-backend#72]
# Description

예약 동시성 이슈와 갑자기 뛰어오르는 트래픽에 대응하기 위해 대기열 시스템을 설계하고자 합니다.

https://github.com/f-lab-clone/ticketing-backend/issues/33 를 참고해 대기열 시스템을 설계해주세요

# To do
- [ ] (**상시**) **관련 자료 요약/기록**
    - 자료에 대한 간단한 정리를 댓글에 첨부 (**언급된 요약을 통해 follow-up** 예정)
    - "link: 글에서는 a와 b의 형식을 사용하여 설계..."

- [ ] 1. 시스템 설계도, 흐름도 등 전반적인 **Diagram 설계**
	- 러프한 손 다이어그램부터 [프로그램](https://hattbatt.tistory.com/m/entry/%EA%B0%9C%EB%B0%9C%EC%9E%90-%EB%8B%A4%EC%9D%B4%EC%96%B4%EA%B7%B8%EB%9E%A8-%ED%88%B4-%EC%B6%94%EC%B2%9C-Excalidraw)을 사용한 다이어그램

- [ ] 2. **단계별 설계** 
   - 가장 간단한 설계 => 문제상황 => 확장(해결방법) => 새로운 문제 상황 => 새로운 확장(해결방법) => ...

- [ ] 3. 구현 가능한 설계 깊이
   - 각 시스템간 API Request Flow 다이어그램 작성 
   - 어떤 데이터를 주고 받아서, 대기열 기능을 가능하게 하는지, 실제 요청 전문(body) 설계
   - 프론트엔드 고려 (이벤트 상세 페이지 : 예약 버튼 => 날짜/시간선택 페이지 => 좌석 선택 페이지 => 최종 정보 입력 후 완료 버튼 => 예약 완료
        - 위 페이지 중 정확히 ‘어디에’ 대기열 기능이 존재하는지 (각 예약 페이지별로 대기열이 있어야 하는지, 처음 예약버튼 클릭시에만 존재하는지, 아니면 최종 ‘완료버튼‘에만 대기열이 존재할 것인지 )
        - 각 페이지마다 API 요청이 존재해야하는지, 마지막 완료버튼클릭시 한번만 Reservation 요청을 Backend로 전송할지 고려 
        -  마지막 예약시 좌석 중복으로 인해 튕기는 등의 행위를 방지할려면 어떻게 할 수 있는지 
        - 물런 위 작업에 많은 리소스가 소모된다면 구현하지 않을 수 있습니다.

# Test Checklist
- [ ] 1. 서버가 현재 가진 처리량보다 수십배 높은 요청이 왔을때 문제 해결
- [ ] 2. 같은 이벤트에 대해 동시 예약을 했을때 동시성 문제 해결

**Comment by junha-ahn** [comment]
# Reference

### Github
[대기열 및 MSA, k8s 기반으로 안정적인 콘서트 예매 사이트](https://github.com/wlwlsus/allback-with-k8s)
- Java 실제 우리가 구현하고자 하는 목표를 완벽하게 구현

[기프티콘 선착순 이벤트 (N명 화면에 남은 대기열 표출)](https://github.com/hgs-study/redis-sorted-set-practice)

[Flab 대기열 프로젝트](https://github.com/f-lab-edu/inqueue/issues/52)

# 발표 자료 (영상)

[[NDC] 실버바인 대기열 서버 설계 리뷰](https://youtu.be/3pO9GJ4zndE)

**Comment by ParkJeongseop** [comment]
https://minjun3021.notion.site/f057d86591a2435da995740d4fe17c04

**Comment by junha-ahn** [comment]
@ParkJeongseop 대기열 시스템 구체화 부탁드립니다.
- 메인 이슈 내용을 점점 더 명확화 (특히 다이어그램 구체적 설계)
- 3번에 기록했듯, 프론트 동작 고려 부탁드립니다.

**Comment by junha-ahn** [comment]
# 고려사항
- 하나의 자원(=Event)에 대한 각 유저의 Wait time을 어떻게 개선할 수 있을까?
- 왜 대기열을 도입해야할까?
- 왜 API 서버로 Non-blocking을 논할까?
- Redis 데이터는 어떻게 구성할까?
- 왜 Kafka를 사용할까?


참고
- [지마켓 대기열 시스템 파헤치기](https://dev.gmarket.com/46)
- [프로모션을 대비한 대기열 시스템 구성하기](https://dev-jj.tistory.com/entry/%ED%94%84%EB%A1%9C%EB%AA%A8%EC%85%98%EC%9D%84-%EB%8C%80%EB%B9%84%ED%95%9C-%EB%8C%80%EA%B8%B0%EC%97%B4-%EC%8B%9C%EC%8A%A4%ED%85%9C-%EA%B5%AC%EC%84%B1%ED%95%98%EA%B8%B0-Redis-WebSocket-Spring)
- [[우아한테크토크] 선착순 이벤트 서버 생존기! 47만 RPM에서 살아남다?!](https://www.youtube.com/watch?v=MTSn93rNPPE)
- [대기열 설계 - @minjun3021](https://minjun3021.notion.site/f057d86591a2435da995740d4fe17c04) 

## 하나의 자원(=Event)에 대한 각 유저의 Wait time을 어떻게 개선할 수 있을까?
> Lock Wait Time 등

**개선할 수 없다.** 동시성 문제를 해결하기 위해 포기해야 한다. 
- 낙관적 락이나 `Auto Commit`을 사용하면 개선 가능하지만 해당 사례에 맞는 개선 방법이 아니다. 


## 왜 대기열 시스템이 필요할까?

그렇다면 각 유저의 Wait Time을 개선할 수 없는데, 왜 대기열을 구현해야할까?

먼저 Wait Time의 증가 말고 다른 어떠한 문제점이 발생할까?
- tomcat이 처리할 수 있는 요청량을 벗어나 request timeout
- hikari pool connection 고갈 등
- **다만 현재 Spike Test에서는 이러한 문제를 만들지 못했다.**

어떤 해결 방법이 있을까?
- Auto-commit : 자원이 몇개 더 생성될 수 있다.
- Transaction and Rollback / Raw Lock
- Queue or Pub/Sub (Redis)

고객의 동접을 대응하지 못할때 FIFO(선입선출) 방식으로 순차적으로 트래픽을 처리하기 위한 방안
- 장애전파(Circuit Breaker)를 막기 위해 대기열 시스템 사용

또한 대기열 시스템은 `Scale out`의 문제점을 해결해준다.
- Scale Out 시간보다 짧은 순간의 트래픽을 처리 가능하다


## 왜 API 서버로 Non-blocking을 논할까?

사례
> Gmarket: 높은 퍼포먼스를 가지고 있는 Redis를 충분히 활용하기 위해 API 서비스는 Non-Blocking 처리가 편리한 `Node.js`으로 작성 

> WebFlux를 기반으로 논블록킹(Non-blocking) 비동기(Async) 프로그래밍을 도입

> 배민 : WebFlux + Netty 논블록킹 서버

서블릿 컨테이너는 **`thread-per-request`** 모델을 따른다

즉 한 쓰레드당 한개의 요청 밖에 처리하지못한다. 그렇게 되면 I/O 작업이 일어날때 쓰레드는 실질적으로 하고있는것이 없지만 다른요청을 처리하지못한다.  그렇게 되면 자원이 부족한 서버(thread를 많이 만들 수 없는)에서 처리할 수 있는 동시 처리량은 매우 제한적일 것이다. 쓰레드를 많이 만든다하더라도 컨텍스트 스위칭 문제가 생겨서 성능에 많은 부담을 주게된다.

특히 이벤트루프기반 비동기 + 논블록킹 Node.js를 사용하면 트래픽을 효율적으로 처리 가능할 것이다 
- Node.js API는 Redis에 빠르게 전달 후 특정 스레드를 할당해 응답을 기다리지 않는다. (= 응답을 기다리는데 특정 스레드나 자원을 할당하지 않는다) 따라서 높은 TPS를 유지할 수 있다.

## Redis 데이터는 어떻게 구성할까?

<img width="692" alt="image" src="https://github.com/f-lab-clone/ticketing-backend/assets/41976906/ed74e114-21ff-401a-b909-63373554396b">

<img width="840" alt="image" src="https://github.com/f-lab-clone/ticketing-backend/assets/41976906/d65524f6-1508-42ce-8dd7-dbbda3bb2c8f">
<img width="858" alt="image" src="https://github.com/f-lab-clone/ticketing-backend/assets/41976906/15d255d5-7382-479b-ab80-42c53085b1d9">

> https://github.com/wlwlsus/allback-with-k8s

Redis는 싱글 스레드로 돌아가기때문에 대기열 등록에대한 동시성 문제에서도 안전

대기열(Watting)과 참가열(Running)을 주로 구분하는것을 확인 가능하다 (또는 Status값을 통해...)
## 왜 카프카를 사용할까?

출처
- https://upcurvewave.tistory.com/482

Redis의 문제점
- 장애에 대한 복구 정책을 수립해야 한다. (Kafka로 더 높은 가용성 달성)

**Comment by junha-ahn** [comment]
구현을 최대한 간단하게 해봅시다
- 최소 API Endpoint를 사용(2~5개)
- Redis 등 외부 Database 사용 X
- Nodejs In-memory Database 사용 (향후 테스트 중 문제점을 발견한다면 그때 개선)

**Comment by junha-ahn** [comment]
<img width="1430" alt="image" src="https://github.com/f-lab-clone/ticketing-backend/assets/41976906/a5b3cdef-591e-409d-9f90-e76c867fefe6">

> Redis 등 외부 DB 사용 X

라고는 했지만 일단 설계 당시에는 Redis 자료 구조를 사용했습니다 (굉장히 편리하네요)

**Comment by junha-ahn** [comment]
<img width="913" alt="image" src="https://github.com/f-lab-clone/ticketing-backend/assets/41976906/9db27a67-d830-4bff-8cd8-82151e8fc253">
<img width="846" alt="image" src="https://github.com/f-lab-clone/ticketing-backend/assets/41976906/827d0972-f5df-4570-9f56-1ab07ab6cd23">

https://parkmuhyeun.github.io/woowacourse/2023-10-04-concurrency/

낙관적 락을 더 시도해보면 좋았다는게 무슨뜻일까?
