### ISSUE TITLE
Grafana Monitoring에 필요한 Dependency 추가

### ISSUE THREAD

**Issue by hihahayoung** [f-lab-clone/ticketing-backend#95]
# Description
현재 그라파나로 상세한 Endpoint에 대한 response 조회가 불가능한 상황입니다. Spring Web MVS에서 optionally parameterized request url을 extract할 수 없어서 UNKNOWN으로 처리한다고 하네요.

# To do
다음 코드를 dependency에 추가해주시면 됩니다.

```
<dependency>
    <groupId>io.github.kdprog</groupId>
    <artifactId>cxf-micrometer-metrics</artifactId>
    <version>1.0.0</version>
</dependency>
```

```
@Bean
public FactoryBeanListener cxfMicrometerBean(final MeterRegistry registry) {
    return new MicrometerFactoryBeanListener(registry);
}
```

참고:
https://stackoverflow.com/questions/55517471/metrics-http-server-requests-seconds-count-in-spring-boot-application-using-cxf

# Test Checklist

**Comment by junha-ahn** [comment]
![image](https://github.com/f-lab-clone/ticketing-backend/assets/41976906/b391048f-8c42-4887-95f8-e781358d7e62)

`http://.../actuator/prometheus`에서 `POST /users/signin` 만 노출되지 않는 상태 (스프링 필터 관련 이슈)

from https://github.com/f-lab-clone/ticketing-backend/pull/96#issuecomment-1742106072

**Comment by junha-ahn** [comment]
Infra 자체적으로 해결 완료
